# Generated by Django 5.2.8 on 2025-11-17 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityAQI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('aqi', models.IntegerField()),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField()),
                ('co', models.FloatField()),
                ('no2', models.FloatField()),
                ('o3', models.FloatField()),
                ('time_fetched', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
