# Generated by Django 5.2.8 on 2025-11-17 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aqiApplication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityAQI',
        ),
    ]
